### ISSUE TITLE
Cockpit doesnt work 

### ISSUE THREAD

**Issue by Spacernova1** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#16]
![{F3B17279-5360-4135-A4D3-805FFFEF5928}](https://github.com/user-attachments/assets/bb629158-08ad-46e8-8f37-7a8bdac51fae)
idk how to fix it

**Comment by giuliodondi** [comment]
there are two Orbiter part variants, looks to me like you picked the one without cockpit internals.
If you did not, check that you installed all dependencies correctly. If the problem persists, I'll reopen the issue.
