### ISSUE TITLE
Kerbals Crouched Down

### ISSUE THREAD

**Issue by BromzeShoe20968** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#17]
Inside the orbiter when I enter kerbal view, they are always crouched down, so I cant look into the HUD properly.
![image_2024-10-08_201455151](https://github.com/user-attachments/assets/b752f089-cf86-46ed-b150-4c8358c723b7)

**Comment by FlandreScarlet1** [comment]
is it a female kerbal?

**Comment by BromzeShoe20968** [comment]
seemed to have been the problem

**Comment by BromzeShoe20968** [comment]
seems to have been the problem
