### ISSUE TITLE
parts not appearing 

### ISSUE THREAD

**Issue by yazzz5x** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#18]
hello, I'am using RP-1 express install and RO and I have some parts that are appearing in the VAB but the majority of the parts are not appearing like the shuttle cockpit

**Comment by giuliodondi** [comment]
This mod does not carry RP-1 configs.

[There is a PR open over at the RP-1 repository about my fork but it hasnt been merged yet](https://github.com/KSP-RO/RP-1/pull/2389). I have nothing to do with that
