### ISSUE TITLE
black textures and the ship is not in hd

### ISSUE THREAD

**Issue by glichdude2011** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#20]
I have black textures on the shuttle from the cockpit to the engine mount and the ship, especially the wings are not in HD and also the back
![imagen_2024-12-08_190352741](https://github.com/user-attachments/assets/093f4f90-59ff-4c15-9962-0b380df3a886)

**Comment by giuliodondi** [comment]
Never seen anything like this, and I even failed to reproduce it deleting files.

Something must have gone terribly wrong with the installation either of the mod or one of the dependencies. Please clean up and start from scratch
