### ISSUE TITLE
SSTU?

### ISSUE THREAD

**Issue by m4ti140** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#5]
Is SSTU actually required? It's not mentioned anywhere in the readme what it's used for, and it's not compatible with RP-1

**Comment by FlandreScarlet1** [comment]
its probably optional then

**Comment by giuliodondi** [comment]
SSTU is used in a couple places to configure some actions and toggleables.
I don't think it's catastrophic if you wish to remove it, although I don't know for sure since I don't use RP-1 and always have SSTU anyways
