### ISSUE TITLE
Orbiter part missing.

### ISSUE THREAD

**Issue by atonsis** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#6]
I followed the installation instructions in the README file and loaded up the game and the Orbiter body/fuselage/cockpit were missing.

I tried reinstalling the package from scratch a second time and had the same issue.

**Comment by 1waverider** [comment]
Is this in RP-1? I have the same issue

**Comment by atonsis** [comment]
> Is this in RP-1? I have the same issue with RP-1, but not with Realism Overhaul

Yeah RP-1. I followed the install instructions. I have some parts like the tail, OMS pods, Et. SRBs and engines. Just don't have cabin, fuselage, or wings.

**Comment by 1waverider** [comment]
It started working for me, I deleted the RP-1 folder and reloaded a few times, you wont have career but you'll have the system

**Comment by atonsis** [comment]
> It started working for me, I deleted the RP-1 folder and reloaded a few times, you wont have career but you'll have the system

Yeah, I'd prefer to have the career play.

**Comment by giuliodondi** [comment]
how was I not notified of this issue? Sorry for reading it so late

The welded Orbiter part is my own addition and so won't be compatible with any mod that's built over the 'standard' SSS set of parts.
I might get around to making an RP-1 patch once I get back into parts modding and figure out how to make it work
