### ISSUE TITLE
Main orbiter parts not found.

### ISSUE THREAD

**Issue by SlainteMaith** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#8]
After following the install instructions (and double-checking that all dependencies are met), there is no fused shuttle cockpit/ payload bay/wing part in the parts list in the VAB.
The tail fin, elevons, and OMS pods are available, however.
It is present in RSS/RO, but is not present in (Sandbox) RP-1.

**Comment by giuliodondi** [comment]
Those parts are gone form this mod. Instead there is a single 'Orbiter' part that is the asembly of all those old parts.

The README explains this as well as why I did it.

**Comment by SlainteMaith** [comment]
Which also does not appear in the parts list.  I didn't _miss_ it.

**Comment by giuliodondi** [comment]
Yeah I'm not managing  the compatibility with RP1, I've been mentioned in that open issue but haven't been requested to do anything about it.
I play sandbox so it's not really a priority of mine
